# DO NOT EDIT THIS FILE.  This file is automatically regenerated as needed.
class Actor < ApplicationRecord

  has_many :roles
  has_many :movies, through: :roles
  has_many :agents, through: :roles

end
