# DO NOT EDIT THIS FILE.  This file is automatically regenerated as needed.
class Agent < ApplicationRecord

  has_many :roles
  has_many :actors, through: :roles
  has_many :movies, through: :roles

end
